### ISSUE TITLE
What happened to DropBeat Website ?

### ISSUE THREAD

**Issue by Draxler** [daftshady/dropbeat#1]
This is what i see on the site when i open it;

![dropbeat](https://cloud.githubusercontent.com/assets/7681671/8716011/f127be18-2b8a-11e5-9a66-37670cf45b22.PNG)

I hope it's only temporary issue.

**Comment by daftshady** [comment]
The server is up again. Thanks!

**Comment by Draxler** [comment]
This was quick . :smile: 
Regards
