### ISSUE TITLE
from celeryapp import app

### ISSUE THREAD

**Issue by Mr-Phoebe** [daftshady/dropbeat#2]
```
from celeryapp import app
```
When run the code, it shows 
```
ModuleNotFoundError: No module named 'celeryapp'
```

And I have installed celery.

**Comment by daftshady** [comment]
Which python version do you use?

**Comment by Mr-Phoebe** [comment]
python 3.6.1

**Comment by daftshady** [comment]
This project doesn't support python 3.x yet.
Python 2 and 3 have different import mechanism.
Please read this https://stackoverflow.com/a/12173406/2920110.
